### ISSUE TITLE
Can you share the implementation of the compared SemiCDNet method？

### ISSUE THREAD

**Issue by lauraset** [wgcban/SemiCD#2]
Hi, @wgcban . I learned a lot from your work. I want to know whether you can share the implementation of the SemiCDNet method you compared? Thank you very much.

**Comment by wgcban** [comment]
Hi @lauraset 

Thank you for your interest in our work, and I am happy that you learned from our work. 

The state-of-the-art methods that I have used for the comparisons in my paper are _not publically available_. Hence, I have implemented those methods on my own and you can find all of those methods by shifting the ``branch``. 

- **s4GAN**: change the branch from ``main`` to ``s4GAN``: https://github.com/wgcban/SemiCD/tree/s4GAN
- **SemiCDNet (TGRS-21)**: change the branch from ``main`` to ``SemiCDNet(TGRS21)``:  https://github.com/wgcban/SemiCD/tree/SemiCDNet(TGRS21)
- **AdvNet**: Change the branch from ``main`` to ``AdvNet``: https://github.com/wgcban/SemiCD/tree/AdvNet
- **RoCD**: Change the branch from ``main`` to ``RoCD``: https://github.com/wgcban/SemiCD/tree/RoCD

I hope this answers your question. Please let me know if you have more questions!

Best,
Chaminda.

**Comment by lauraset** [comment]
Hi, @wgcban . Thank you for your detailed response. You are really a nice person. 
One issue confused me. That is the high similarity  between your method with the CCT (cross-consistency training) method.  Actually, I guess that the temporal consistency (e.g., the high similarity of unchanged areas and the high dissimilarity of changed areas between bi-temporal images) embedded in the change detection is not utilized yet. 
I guess this point may differentiate the  change detection task from the semantic segmentation one for the CCT method. Anyway, thank you for your help.

Best regards,
Yinxia Cao.

**Comment by wgcban** [comment]
@lauraset 

Yes, you are correct that the proposed method is somewhat similar to CCT; however, the main idea that we want to convey from this work is that the **cluster assumption** exists even for bitemporal images in the **deep feature difference domain** and consistency training can be used for semi-supervised (SS) change detection, while CCT considers SS semantic segmentation with RGB images, not bi-temporal images.

Yes, I agree with your point that our method does not integrate the time consistency of change and no-change regions, and I will address this in my future work. Thanks for your suggestion.

Best,
Chaminda.

**Comment by lauraset** [comment]
@wgcban , Thank you for your nice help. I have no further questions.

**Comment by wgcban** [comment]
Nice, I am closing this issue.

**Comment by wgcban** [comment]
Nice, I am closing this issue.

**Comment by maozan** [comment]
> 

Hi@lauraset, could you further share your thoughts on temporal consistency?
