### ISSUE TITLE
Downloading link of processed datasets

### ISSUE THREAD

**Issue by LiheYoung** [wgcban/SemiCD#3]
Hi,

Could you please provide a Google Drive link for downloading the two processed datasets? Since I can not download from dropbox, the process will fail each time it is going to finish. Thanks very much.

**Comment by wgcban** [comment]
@LiheYoung
Hey did you try the command line:
Run this command in your terminal:
`wget https://www.dropbox.com/sh/i54h8kkpgar1s07/AAA0rBAFl9UZ3U3Z1_o46UT0a/DSIFN-CD-256.zip`

**Comment by LiheYoung** [comment]
It works. Thanks a lot.
