### ISSUE TITLE
heatmap visualization

### ISSUE THREAD

**Issue by Yanll2021** [wgcban/SemiCD#4]
I am very sorry to bother you. I am very interested in your research direction. May I ask where I can find your visual code?

**Comment by wgcban** [comment]
@Yanll2021 Sorry for the late reply. The codes used to visualize the cluster assumption is available here: https://www.dropbox.com/sh/lrkepm54x9w6lww/AACGpoBoWvGsyKdCMsjk9OxZa?dl=0
