### ISSUE TITLE
about the best_model.pth

### ISSUE THREAD

**Issue by maozan** [wgcban/SemiCD#5]
Excuse me, is the released model.pth file re-trained, it seems to be a little bit more accurate than what is reported in the paper.

**Comment by wgcban** [comment]
@maozan No, it is not re-trained - this is the model used to compute the metrics that are reported in the paper. Sometimes it may give slightly bad/good results depending on your GPU, and package versions.

**Comment by maozan** [comment]
> @maozan No, it is not re-trained - this is the model used to compute the metrics that are reported in the paper. Sometimes it may give slightly bad/good results depending on your GPU, and package versions.

Thank you, the SemiCD is an impressive study. Looking forward to your more impactful achievements. @wgcban

**Comment by wgcban** [comment]
@maozan Thank you.
