### ISSUE TITLE
about comparison experiment

### ISSUE THREAD

**Issue by Ley-lele** [wgcban/SemiCD#6]
I wonder how can u get the results of SemiCDNet，cause I cannot find their codes and the same experiment from their paper. Did u repetition the SemiCDNet？
![image](https://user-images.githubusercontent.com/75935402/196879317-2e490795-f6a9-461d-8064-99fbebf743aa.png)

**Comment by wgcban** [comment]
@Ley-lele
Yes, I reimplemented their paper and this is my best implementation (sota methods are in the other branches) : 

- SemiCDNet: https://github.com/wgcban/SemiCD/tree/SemiCDNet(TGRS21)

**Comment by Ley-lele** [comment]
> @Ley-lele Yes, I reimplemented their paper and this is my best implementation (sota methods are in the other branches) :
> 
> * SemiCDNet: https://github.com/wgcban/SemiCD/tree/SemiCDNet(TGRS21)

Brilliant! Thanks a lot!
