### ISSUE TITLE
Can you share the Comparison Experiments Pre-trained models

### ISSUE THREAD

**Issue by mancyli** [wgcban/SemiCD#7]
Hello, @wgcban ,
I am interested in your work, and want to do some Comparison Experiments, can you share the other Comparison Experiments Pre-trained models? Thank you very much !
Best wishes !

**Comment by wgcban** [comment]
@mancyli Thank you for the interest. You can find other sota methods by changing the branch. Codes for those methods were not publicly available so i reimplemented those methods for comparisons.

**Comment by mancyli** [comment]
ok, Thanks for your reply ~ 🙇‍♀️🙇‍♀️
