### ISSUE TITLE
The train.py file could not be found

### ISSUE THREAD

**Issue by yyf17** [wgcban/SemiCD#8]
Very nice work. Thanks so much for sharing your hard work.
When I was training, I got an error that the train.py file could not be found. The specific error screenshot is as follows:
![image](https://user-images.githubusercontent.com/34536352/233247861-e7490157-2e1a-4b9d-a315-64f1bdccb90a.png)

Thanks!

**Comment by wgcban** [comment]
@yyf17 Make sure you provide correct path to the train.py or you are in the correct directory.

**Comment by yyf17** [comment]
@wgcban 
I am using the main branch, and the train.py file cannot be found in the root directory of this branch. Here is a screenshot of my project:
![image](https://user-images.githubusercontent.com/34536352/233530732-a4b453ff-6525-4ba9-a304-1b3b85eb7573.png)

**Comment by wgcban** [comment]
@yyf17 my bad, i renamed the train.py to train_semicd.py.

**Comment by wgcban** [comment]
@yyf17 This issue is fixed now, I renamed the train_semicd.py to train.py in the main branch.
